extends: site.yaml

mode: production
media_url: /jakevdp/media
base_url: /jakevdp
deploy_root: deploy_production

publisher:
    ssh:
        type: hyde.ext.publishers.ssh.SSH
        username: jakevdp
        server: jakevdp.ovid.u.washington.edu
        target: /rc00/d68/jakevdp/public_html